# Generated by Django 4.0.4 on 2022-05-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_featuredbooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedBooks',
        ),
    ]
